version: '3.3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.1
    networks:
      - elknet

  kibana:
    image: docker.elastic.co/kibana/kibana:6.7.1
    ports:
      - "5601:5601"
    networks:
      - elknet

  rabbit:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - elknet
      

  logstash:
    image: docker.elastic.co/logstash/logstash:6.7.1
    volumes:
      - ./logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    networks:
      - elknet

networks:
  elknet:
    driver: bridge